[server]
address = "127.0.0.1"
port = 8501
headless = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#008E99"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF3F7"
textColor = "#112344"
font = "sans serif"
